# Generated by Django 3.0.7 on 2020-06-16 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_at',
            field=models.CharField(default=datetime.datetime.now, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='http://e-distribuidor.com.br/images/not_image.png', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='quant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Unitario', 'Unitário'), ('Caixa', 'Caixa'), ('Peca', 'Peça'), ('Metro', 'Metro')], default='Unitario', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='value_hospital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='product',
            name='value_representante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
