# Generated by Django 3.0.7 on 2020-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200616_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='createAt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value_hospital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value_representante',
        ),
        migrations.AddField(
            model_name='product',
            name='valueHospital',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='valueRepresentante',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/gianini-manutencao.appspot.com/o/noImage.gif?alt=media&token=c6cca84a-595f-4efb-9ec1-6e71d21def77', max_length=1000),
        ),
    ]
